disquaire/disquaire/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from store import views
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

urlpatterns = [
    url(r'^store/', include(('store.urls', 'store'), namespace='store')),
    url(r'^content/', admin.site.urls),
    url(r'^$', views.index, name='home')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

disquaire/store/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.listing, name="listing"),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name="detail"),
    # url(r'^artist/(?P<artist_name>[A-Za-z|-]+)/$', views.artist),
    url(r'^search/$', views.search, name="search"),
]

disquaire/store/models.py
from django.db import models

# Create your models here.
# ARTISTS = {
#     "youssou-ndour" : {"name" : "Youssou Ndour"},
#     "wally-seck" : {"name" : "Wally Seck"},
# } 

# ALBUMS = [
#     {"name" : "Bercy", "artists" : [ARTISTS["youssou-ndour"]]},
#     {"name" : "Senegal", "artists" : [ARTISTS["wally-seck"]]}
# ]

class Artist(models.Model):
    name = models.CharField(max_length=200, unique=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "artist"

class Contact(models.Model):
    email = models.EmailField(max_length=100, verbose_name="Email", unique=True)
    name = models.CharField(max_length=200, verbose_name="Nom")
    def __str__(self):
        return self.name

class Album(models.Model):
    reference = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    picture = models.URLField()   
    artists = models.ManyToManyField(Artist, related_name='albums', blank=True)
    def __str__(self):
        theArtists=", ".join([artist.name for artist in self.artists.all()])
        return "{} / {}".format(self.title, theArtists)

class Booking(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    contacted = models.BooleanField(default=False)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    album = models.OneToOneField(Album,on_delete=models.CASCADE)
    def __str__(self):
        return self.contact.name

disquaire/store/forms.py
from django import forms
from .models import Contact

class ContactForm( forms.ModelForm ):
    class Meta:
        model = Contact
        fields = ["name", "email"]
    

disquaire/store/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Album, Artist, Contact, Booking 
from .forms import ContactForm

# Create your views here.
def index(request):
    albums = Album.objects.filter(available=True).order_by('-created_at')[:12]
    context = {'albums': albums}
    return render(request, 'store/index.html', context)


def detail(request, album_id):
    id = int(album_id) # make sure we have an integer.
    album = get_object_or_404(Album, pk=id)
    artists_name = ", ".join([artist.name for artist in album.artists.all()])
    
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            email=request.POST.get('email')
            form=Contact.objects.filter(email=email).get()    

        booking = Booking(
                contact=form,
                album=album
                ).save()
        album.available=False
        album.save()
        context={'booking':booking}
        return render(request, 'store/merci.html', context)    
                
    else:
        form = ContactForm()
    context = {
        'album_title': album.title,
        'artists_name': artists_name,
        'album_id': album.id,
        'thumbnail': album.picture,
        'form': form 
    }

    return render(request, 'store/detail.html', context)

def search(request):
    query = request.GET.get('query')
    title = request.GET.get('title')
    if not query:
        albums = Album.objects.all()
    else:
        albums = Album.objects.filter(title__contains=query)
 
    title = "Resultats pour la requete %s"%query
    context = {
        'albums': albums,
        'title': title
    }         
    return render(request, 'store/search.html', context)   


def listing(request) :
    albums_list = Album.objects.all()
    paginator = Paginator(albums_list,2)
    page = request.GET.get('page')
    try:
        albums = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        albums = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        albums = paginator.page(paginator.num_pages)
    context = {
        'albums': albums,
    }         
    return render(request, 'store/listing.html', context)

disquaire/store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Casual - Start Bootstrap Theme</title>


    {% load static %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'store/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'store/css/business-casual.css' %}" rel="stylesheet">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Disquaire</div>
    <div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="{% url 'home' %}">Disquaire</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'home' %}">Accueil</a>
                    </li>
                    <li>
                        <a href="{% url 'store:listing' %}">Tous les disques</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">

                {% block content %}
                {% endblock %}
                
            </div>
        </div>



    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'store/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

disquaire/store/templates/store/detail.html
{% extends 'store/base.html' %}


{% block content %}
<hr>
<h1 class="intro-text text-center">{{ album_title }}</h1>
<hr class="detail-separator">
<div class="col-md-6">
  <img src="{{ thumbnail }}" alt="{{ album_title }}" class="img-responsive">
</div>
<div class="col-md-6">
  <div style="margin-bottom:45px">
    <h2 class="text-center artist_name">Artistes</h2>
    <p>{{ artists_name }}</p>
  </div>

  <h2 class="text-center artist_name">Réserver {{ album_title }}</h2>
  <p style="margin-bottom: 20px;">Demandez-nous de mettre de côté {{ album_title }} et venez le chercher dès demain en magasin ! </p>
  {% include 'store/form_detail.html' with id=album_id %}

</div>


{% endblock %}

disquaire/store/templates/store/form_detail.html
{% load crispy_forms_tags %}
<form class="form-inline" action="{% url 'store:detail' album_id=id %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-success">Réserver</button>
  </form>

disquaire/store/templates/store/index.html
{% extends 'store/base.html' %}

{% block content %}

    {% include 'store/list.html' with list_title="Nos derniers disques" %}

{% endblock %}

disquaire/store/templates/store/list.html
{% if albums|length_is:"0" %}
    <div class="text-center">
        palsamb ! Nous n'avons trouve aucun resultat a cette requete. Meme pas de quoi se ronger la chique ! 
        Partez de nouveau a labordage.
    </div>
{% else %}    

    <div class="col-lg-12">
        <hr>
        <h2 class="intro-text text-center">{{ list_title }}   
        </h2>
        <hr class="detail-separator">
    </div>


    {% include 'store/search_form.html' %} <!-- NEW -->


    {% for album in albums %}
        <div class="col-sm-4 text-center">
            <a href="{% url 'store:detail' album_id=album.id %}">
                <img class="img-responsive" src="{{ album.picture }}" alt="{{ album.title }}">
            </a>
            <h3><a href="{% url 'store:detail' album_id=album.id %}">{{ album.title }}</a></h3>
            {% for artist in album.artists.all %}
                <p>{{ artist.name }}</p>
            {% endfor %}    
        </div>
        {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div> 
        {% endif %}  
    {% endfor %}   
    
    <div class="clearfix"></div>
    <nav aria-label="...">
      <ul class="pager">
        {% if albums.has_previous %}
            <li><a href="?page={{ albums.previous_page_number }}">Précédent</a></li>
        {% endif %}
        {% if albums.has_next %}
            <li><a href="?page={{ albums.next_page_number }}">Suivant</a></li>
        {% endif %}
      </ul>
    </nav>    

{% endif %}

disquaire/store/templates/store/listing.html
{% extends 'store/base.html' %}

{% block content %}

    {% include 'store/list.html' with list_title='Tous nos disques' %}

{% endblock %}

disquaire/store/templates/store/merci.html
{% extends 'store/base.html' %}
{% block content %}

<hr>
    <h1 class="intro-text text-center">Merci !</h1>
    <hr class="detail-separator">
    <p>L'album <em>{{ booking.album.title }}</em> vient d'être retiré des rayonnages.
        Une main délicate a déposé votre nom, <em>{{ booking.contact.name }}</em> sur sa couverture et l'a rangé en vous attendant. Dépêchez-vous ! <em>{{ album_title }}</em> trépigne d'impatience et chante déjà vos louanges.</p>
    <hr>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ZSbuikMdgqA" frameborder="0" allowfullscreen></iframe>
    </div>

{% endblock %}

disquaire/store/templates/store/search.html
{% extends 'store/base.html' %}

{% block content %}

    {% include 'store/list.html' with list_title=title %}

{% endblock %}

disquaire/store/templates/store/search_form.html
<div class="col-lg-12 detail-separator">
    <form class="col-md-6 col-md-offset-3 text-center" action="{% url 'store:search' %}" method="get" accept-charset="utf-8">
      <div class="form-group">
        <label for="searchForm">Chercher un disque</label>
        <input id="searchForm" class="form-control" name="query">
      </div>
      <span class="help-block" id="helpBlock">Trouvez le CD de vos rêves en tapant son titre ou le nom d'un des artistes.</span>
    </form>
  </div>
  